title: "GAP" # System for Computational Discrete Algebra"
subtitle: "System for Computational Discrete Algebra"
theme: just-the-docs
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.gap-system.org" # the base hostname & protocol for your site, e.g. http://example.com

docsurl: "https://docs.gap-system.org"

color_scheme: lightgap

exclude:
  - "*.g"
  - "/README.md"
  - "/etc"
  - "/tmp"
  - "/ForumArchive"
  - "/ForumArchive2"
  - "/HostedGapPackages"
  - "/Manuals"

include:
  - ".htaccess"

keep_files:
  - "ForumArchive"
  - "ForumArchive2"

liquid:
  error_mode: warn
  #strict_variables: true # commented out because it isn't supported by just-the-docs
  strict_filters: true

math: mathjax

callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red

defaults:
  - scope:
      path: ""
    values:
      has_toc: false
      toc: nil
      subtoc: nil
      subsubtoc: nil

logo: "assets/logo/light/gaplogo.svg"

favicon_ico: "PLACEHOLDER" # actual path is set in scss files

# External navigation links
nav_external_links:
  - title: GAP on GitHub
    url: https://github.com/gap-system/gap

aux_links:
  "GAP on GitHub":
    - "//github.com/gap-system/gap"

sass:
  quiet_deps: true # https://github.com/just-the-docs/just-the-docs/issues/1541
  silence_deprecations: ['import'] # https://github.com/just-the-docs/just-the-docs/issues/1607
